### ISSUE TITLE
No file named trainval.txt

### ISSUE THREAD

**Issue by michaelyan-coupa** [LarryJiang134/Image_manipulation_detection#10]
Hi, I am getting this error:

Traceback (most recent call last):
  File "main_create_training_set.py", line 25, in <module>
    imdb = get_imdb("voc_2007_trainval")
  File "/home/ubuntu/Image_manipulation_detection/lib/datasets/factory.py", line 48, in get_imdb
    return __sets[name]()
  File "/home/ubuntu/Image_manipulation_detection/lib/datasets/factory.py", line 24, in <lambda>
    __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
  File "/home/ubuntu/Image_manipulation_detection/lib/datasets/pascal_voc.py", line 41, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/ubuntu/Image_manipulation_detection/lib/datasets/pascal_voc.py", line 101, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: /home/ubuntu/Image_manipulation_detection/data/VOCDevkit2007/VOC2007/ImageSets/Main/trainval.txt

**Comment by moulicm111** [comment]
Hi,Please tell me how you solved this ?
